### ISSUE TITLE
Open ticket so people can ask questions here instead of a PR

### ISSUE THREAD

**Issue by alfiedotwtf** [alfiedotwtf/AABillFAQ#1]
I'll update the repo at the end of each day.

**Comment by Notoh** [comment]
Are there any important certificate authorities within Australia? If there are, are these potentially comprised and no longer trustable?

**Comment by alfiedotwtf** [comment]
Thanks for the first issue!

Symantec are in Melbourne, but AFAIK their work is on antivirus (with their CA work done in the UK). But there could be more.

I'll update the repo at the end of each day.

**Comment by parsect** [comment]
Questions (low end for punters)
Should we update our phones?
Should we update apps?
Should we update computers?
What is open source and how does it relate to this?
What is Signal
Why is Signal different to WhatsApp?
Please explain encryption?
What is the difference between HTTP and HTTPS?
Can encryption be broken?
How will they see what I am doing/ sending? (key loggers/ screen cap)
Can I get a refund for my phone?
I have nothing to fear, why should I worry?
Why is encryption important?

**Comment by Frederick888** [comment]
What we need to do to repeal this law? Is it even possible?

**Comment by Frederick888** [comment]
Another one: how does this law affect working visa holders/permanent residents?

**Comment by Yuxianray** [comment]
What are some popular applications/software maintained by Australia-based devs likely to be targeted by the government for introducing backdoors into? (Social media, banking etc)

**Comment by brevenk** [comment]
How will opensource software such as Firefox and Linux Distros be affected? 
Wouldn't updates that include large blocks of closed source software be obvious?
Under most open source software licenses, wouldn't open source software vendors be required to inform users that some of the code is going to be closed source?

**Comment by brevenk** [comment]
Is it possible that the Government could avoid the restriction of creating systemic weakness, by forcing tech companies to serve malicious updates to specific targets. In this way, only the target's system would posses a backdoor, whilst non-targets are provided with secure updates.

**Comment by Frederick888** [comment]
@brevenk That's not really feasible I reckon. Once a tool that can target a single individual is created, no one can ensure it won't be (ab)used to target other innocent people. And actually this involves with coding the logic which enables downloading effectively malware into **everyone's** devices, how is that different from the AA bill and not causing 'systemic weakness'?

Plus both the coalition and the Labor 1. don't want to be accused of being a 'national security concern' 2. crave the power of seizing any data whenever they want 3. well understand that the vast majority just don't give a sh*t to this bill, why wouldn't they make it as powerful and convenient as possible?

**Comment by Frederick888** [comment]
@Yuxianray Atlassian's at the top of the list.

**Comment by alam0rt** [comment]
I also posted a question in a new issue but I'll ask here too. Are warrant canaries a viable way to alert employers / the public that you have been compelled to introduce a backdoor?

**Comment by silarsis** [comment]
sorry, raised PR - can we please have a link to the bill itself added to the page, just for handy reference? I think https://www.aph.gov.au/Parliamentary_Business/Bills_Legislation/Bills_Search_Results/Result?bId=r6195 is the best option...?

**Comment by cyphar** [comment]
The best link would be https://www.legislation.gov.au/Details/C2018A00148 or http://www.austlii.edu.au/.

**Comment by cyphar** [comment]
> Under most open source software licenses, wouldn't open source software vendors be required to inform users that some of the code is going to be closed source?

I would expand this to, what would happen if a TCN required us to violate a copyright license? (For instance, we are forced to add a backdoor to a GPLv3+ work and then ship it to a user -- legally we have to give them the source code but this would disclose the backdoor.)

**Comment by parsect** [comment]
Refusing to give a password seems to have enough potential penalty to be a trigger for the Assistance and Access act- is that right?

**Comment by Frederick888** [comment]
@parsect Yes. Google `australia refuse give password` you'd find tons of results.

**Comment by Johndowe** [comment]
do politicians ever get tired of using terrorism, child porn and drugs as an excuse to act like fucking retards?

**Comment by alfiedotwtf** [comment]
> Questions (low end for punters)
> Should we update our phones?
> Should we update apps?
> Should we update computers?
> What is open source and how does it relate to this?
> What is Signal
> Why is Signal different to WhatsApp?
> Please explain encryption?
> What is the difference between HTTP and HTTPS?
> Can encryption be broken?
> How will they see what I am doing/ sending? (key loggers/ screen cap)
> Can I get a refund for my phone?
> I have nothing to fear, why should I worry?
> Why is encryption important?

Probably not a question for the FAQ, but thanks for your questions.

**Comment by alfiedotwtf** [comment]
> What we need to do to repeal this law? Is it even possible?

Added. Thanks!

**Comment by alfiedotwtf** [comment]
> Another one: how does this law affect working visa holders/permanent residents?

Added. Thanks.

**Comment by alfiedotwtf** [comment]
> What are some popular applications/software maintained by Australia-based devs likely to be targeted by the government for introducing backdoors into? (Social media, banking etc)

Thanks for your question, but probably not suited for the FAQ.

**Comment by alfiedotwtf** [comment]
> How will opensource software such as Firefox and Linux Distros be affected?
> Wouldn't updates that include large blocks of closed source software be obvious?
> Under most open source software licenses, wouldn't open source software vendors be required to inform users that some of the code is going to be closed source?

Thanks. Added

**Comment by alfiedotwtf** [comment]
> Is it possible that the Government could avoid the restriction of creating systemic weakness, by forcing tech companies to serve malicious updates to specific targets. In this way, only the target's system would be updated to posses a backdoor, whilst non-targets are provided with secure updates.

Added, but to me this is the whole point of Notices and how they think they're going to get around building generic backdoors and dragnets.

**Comment by alfiedotwtf** [comment]
> @Yuxianray Atlassian's at the top of the list.

BitBucktet for sure.

**Comment by alfiedotwtf** [comment]
> sorry, raised PR - can we please have a link to the bill itself added to the page, just for handy reference? I think https://www.aph.gov.au/Parliamentary_Business/Bills_Legislation/Bills_Search_Results/Result?bId=r6195 is the best option...?

Done :)

**Comment by alfiedotwtf** [comment]
> The best link would be https://www.legislation.gov.au/Details/C2018A00148 or http://www.austlii.edu.au/.

Ah. Yep, you're right. I'll switch to the HTML version now.

**Comment by alfiedotwtf** [comment]
> what would happen if a TCN required us to violate a copyright license? (For instance, we are forced to add a backdoor to a GPLv3+ work and then ship it to a user -- legally we have to give them the source code but this would disclose the backdoor.)

Added. Wow, that's a really interesting question. Thinking through, maybe they've thought of that given that you're no longer subject to civil liabilities if complying to a warrant or Notice.

**Comment by alfiedotwtf** [comment]
> Refusing to give a password seems to have enough potential penalty to be a trigger for the Assistance and Access a

Added. Thanks

**Comment by alfiedotwtf** [comment]
> as

Probably not a question for the FAQ, but it looks like the answer is no :/

**Comment by alfiedotwtf** [comment]
To limit spam, I'm going to close this ticket and update the docs to say create a new one.

Thanks everyone for your questions and comments!
