### ISSUE TITLE
Can we  make the government pay for our loss of income now that australian IT workers are considered "Bad actors"

### ISSUE THREAD

**Issue by wmealing** [alfiedotwtf/AABillFAQ#10]
Since the government has affected our future income and employment for a large number of Australian 
 tech workers and Australian products overseas what financial aid will the government provide to ensure we can be reskilled into farming , mining or political work ?  With possible other benefits for loss of income due to these new laws.

**Comment by alfiedotwtf** [comment]
Thanks for the question, but see https://github.com/alfiedotwtf/AABillFAQ/issues/4
