### ISSUE TITLE
Applicability of law when it is not obvious if a backdoor is the result of a TCN or othewise

### ISSUE THREAD

**Issue by liamosaur** [alfiedotwtf/AABillFAQ#13]
- A technical person reviewing code/config/state finds software/configuration that they believe may be the result of a TCN, *or* may be a malicious backdoor. If they communicate information about what they have found to another person, can they be in violation of the rules of a TCN they are unaware of?
(Context for question: concern around chilling effects the law may have on reporting/discussing non-AAbill backdoors

**Comment by alfiedotwtf** [comment]
Thanks for the question. Yep, this is highly important for local researcher. Added.
