### ISSUE TITLE
Ratification of Article 12

### ISSUE THREAD

**Issue by printfJess** [alfiedotwtf/AABillFAQ#16]
To quote the UN Declaration of Human Rights, "No one shall be subjected to arbitrary interference with his privacy, family, home or correspondence, nor to attacks upon his honour and reputation. Everyone has the right to the protection of the law against such interference or attacks."

Interference with an individual's privacy/communication on the basis of an investigation under AABill would not be deemed "arbitrary".

However, compliance with a TCN has the capacity to undermine the security of software used as a communications or storage medium by many other individuals, who should ordinarily be protected by law.

In cases like that, where there is technically  no other option but to break the software encryption for everyone, can Article 12 and/or other domestic legislation relating to privacy protection be used as a legal basis for not complying with a TCN?

**Comment by alfiedotwtf** [comment]
This is personally important to me. Thanks for the question. Added.
