### ISSUE TITLE
The use of Open Source Software and upstream changes.

### ISSUE THREAD

**Issue by fubarhouse** [alfiedotwtf/AABillFAQ#17]
I would like to know how this bill will impact the use of open source software when stable and reliable software have licenses which provide no enterprise support and no obligation to change for its users.

This is particularly alarming because security fixes are common-place and very visible to the public. When changes are requested to introduce security problems, everybody knows about them or can get access to them without much difficulty beyond security advisory notices.

* What are the obligations of open source maintainers for software directed to break down security?
* If there is no maintainer (passed away etc), will it be mandated to fork a repository to take on additional responsibility and capability just to introduce security flaws? How will this work, its resources and the sustainability of said problems be funded - even in the event no funding or liquidation is occurring.
* Upstream changes required to meet a Capability Notice for code maintained outside of Australia.
* What will happen to projects which have multiple parties across the world including if only one Australian citizen is maintaining?
* Are maintainers expected to introduce security flaws to comply with a Notice and not consult other maintainers, stakeholders or the community - even when tight approval processes are already in place to prevent the scenario being imposed?

**Comment by alfiedotwtf** [comment]
Thanks for the questions! Added.
