### ISSUE TITLE
Primary initial targets

### ISSUE THREAD

**Issue by justsee** [alfiedotwtf/AABillFAQ#19]
Telstra and Optus are key core telco companies.

It's not unreasonable to imagine that covert assets from intelligence agencies are already embedded in these organisations.

They are involved in development, support and distribution of key endpoint hardware (routers / mobile phones).

1. *legal question* - what, if any, legislation allows for intelligence agencies to insert covert assets into these orgs
2. *logic question* - does it follow that initial targets for notices would be to their own assets? In this scenario they are simply using the legal cover to undertake work using their own network of employees, who would not provide any resistance, trigger any dramatic conscientious objection in the media etc.
3. *technical question* - what malware vectors are feasible / likely within these organisations? Payloads on support websites targeting end-users, Android / iOS software updates (what software, how would it avoid conflicting with OEM updates from Apple etc), modified software on router hardware etc

**Comment by alfiedotwtf** [comment]
Thanks for the questions.

1) Added

2) Not really a question for the FAQ

3) Not really a question for the FAQ.
