### ISSUE TITLE
Add link in README to full text of the AABILL

### ISSUE THREAD

**Issue by jane-scott** [alfiedotwtf/AABillFAQ#20]
Add link so people can peruse the text of the full bill 

https://parlinfo.aph.gov.au/parlInfo/download/legislation/bills/r6195_aspassed/toc_pdf/18204b01.pdf;fileType=application%2Fpdf#search=%22legislation/bills/r6195_aspassed/0000%22

**Comment by alfiedotwtf** [comment]
Thanks for that. Adding now.

**Comment by alfiedotwtf** [comment]
Done. Thanks again!
