### ISSUE TITLE
SCV and state-level protection questions

### ISSUE THREAD

**Issue by charlingli** [alfiedotwtf/AABillFAQ#23]
How does the bill impact New Zealand citizens on a Special Category Visa (able to work/live indefinitely in Australia, but not permanent residents/Australian citizens)?

What, if any, avenues exist at the state level either through legislation or the judicial system to protect/offer legal recourse for developers served with a notice?

**Comment by alfiedotwtf** [comment]
I think your first question is now covered in the "Top 5" set of questions, but I've added your second question. Thanks for your questions :)
