### ISSUE TITLE
Specifications/Coding Standards for Backdoor Code

### ISSUE THREAD

**Issue by esb** [alfiedotwtf/AABillFAQ#24]
If you are co-opted to create or modify code to create a backdoor under the legislation, are there any limitations or directives on how the code must be written? If you are creating this code without the knowledge of your employer and you 'accidentally' forget to follow the company coding standards, which makes the unauthorized code update easy to find, are you in breach of the legislation, or do you have plausible deniability?

**Comment by alfiedotwtf** [comment]
Hehe. The quotes around accidentally probably aren't going to help you in court :)

I've added the vibe of your question along with #22, but plausible deniability is an interesting angle.
