### ISSUE TITLE
non question activism

### ISSUE THREAD

**Issue by parsect** [alfiedotwtf/AABillFAQ#3]
Shall we just dump ideas here or have a repository (perhaps a little more closed to MPs) where we can throw our thoughts and see if they are worth running with?
I am thinking along the lines of
activism, media, sites, disruption, strikes, using skills/ resources to fight

**Comment by alfiedotwtf** [comment]
Feel free to add anything you feel is relevant. I think it's important to capture everything, so just dump as much as you want, and we can reorg later.

As for the questions to lawyers, I'll summarise and filter all questions once we have a significant chunk of work to be worth their time.

**Comment by SMG999** [comment]
No point in using a private repo as they'd find a way in anyway and we should make it obvious that we're angry

**Comment by alfiedotwtf** [comment]
I think https://alp.fail/ did a good job. Closing this now, but if you have any questions to add to the FAQ, please create another ticket.
