### ISSUE TITLE
Complying with similar laws in multiple countries.

### ISSUE THREAD

**Issue by gregeryb** [alfiedotwtf/AABillFAQ#31]
The assumption in this bill is that only the Australian government will receive these capabilities. I believe this is incorrect as multiple countries have lawful interception laws. If I'm to create a backdoor for Australia I would also give the same backdoor to Russia, China, Uzbekistan, Indonesia, Syria, Israel, Italy, Germany, etc. because an app on the app store can be delivered to all these countries and would have to comply with local laws. 

I see the problem with this law is it is vulnerable to 'mutually assured destruction', i.e. if Australia doesn't want these capabilities being used to spy on members of parliament then that's too bad if compliance with Russian or Chinese laws means the capability is not so discerning.

**Comment by gregeryb** [comment]
Spoke too soon. https://venturebeat.com/2019/02/01/apple-will-reportedly-store-russian-user-data-locally-possibly-decrypt-on-request/

**Comment by alfiedotwtf** [comment]
Thanks for bringing this to my attention. I was assured by several people that Apple would take the moral high ground and would never give in to any country. Looks like everyone has their price :(
