### ISSUE TITLE
My Gov and .gov.au apps

### ISSUE THREAD

**Issue by parsect** [alfiedotwtf/AABillFAQ#5]
Centrelink require people use mygov to upload documents and communicate. Do Australians have to use this app if they fear it is compromised? What options are there?

**Comment by politas** [comment]
Shouldn't be affected by these laws at all. The government already has access to all that data.

**Comment by parsect** [comment]
@politas  more along the lines of nothing stopping government adding a script to mygov that installs a keylogger/ screen streamer to watch Signal messages.

**Comment by parsect** [comment]
any executable from .gov.au is suspect surely

**Comment by alfiedotwtf** [comment]
I understand your concerns, but I'm closing this issue as it's not a question for the FAQ.
